//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRES
    {
        public ADRES()
        {
            this.PRACOWNIK = new HashSet<PRACOWNIK>();
            this.ZAWODNIK = new HashSet<ZAWODNIK>();
        }
    
        public decimal ID_ADRESU { get; set; }
        public string MIEJSCOWOSC { get; set; }
        public string ULICA { get; set; }
        public string KOD_POCZTOWY { get; set; }
        public string NR_BUDYNKU { get; set; }
        public string NR_MIESZKANIA { get; set; }
    
        public virtual ICollection<PRACOWNIK> PRACOWNIK { get; set; }
        public virtual ICollection<ZAWODNIK> ZAWODNIK { get; set; }
    }
}
