//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRES_OBIEKTU
    {
        public ADRES_OBIEKTU()
        {
            this.OBIEKT_SPORTOWY = new HashSet<OBIEKT_SPORTOWY>();
        }
    
        public decimal ID_ADRESU_OBIEKTU { get; set; }
        public string MIEJSCOWOSC { get; set; }
        public string ULICA { get; set; }
        public string NR_BUDYNKU { get; set; }
        public string NR_MIESZKANIA { get; set; }
    
        public virtual ICollection<OBIEKT_SPORTOWY> OBIEKT_SPORTOWY { get; set; }
    }
}
