//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADRES> ADRES { get; set; }
        public DbSet<ADRES_OBIEKTU> ADRES_OBIEKTU { get; set; }
        public DbSet<DRUZYNA> DRUZYNA { get; set; }
        public DbSet<OBIEKT_SPORTOWY> OBIEKT_SPORTOWY { get; set; }
        public DbSet<POZYCJA> POZYCJA { get; set; }
        public DbSet<PRACOWNIK> PRACOWNIK { get; set; }
        public DbSet<PRACOWNIK_DRUZYNA> PRACOWNIK_DRUZYNA { get; set; }
        public DbSet<PRACOWNIK_OBIEKT> PRACOWNIK_OBIEKT { get; set; }
        public DbSet<STANOWISKO> STANOWISKO { get; set; }
        public DbSet<ZAWODNIK> ZAWODNIK { get; set; }
    }
}
