//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBIEKT_SPORTOWY
    {
        public OBIEKT_SPORTOWY()
        {
            this.PRACOWNIK_OBIEKT = new HashSet<PRACOWNIK_OBIEKT>();
        }
    
        public decimal ID_OBIEKTU { get; set; }
        public string NAZWA_OBIEKTU { get; set; }
        public Nullable<System.DateTime> DATA_NABYCIA { get; set; }
        public Nullable<System.DateTime> DATA_SPRZEDAZY { get; set; }
        public string OPIS_OBIEKTU { get; set; }
        public Nullable<decimal> ID_ADRESU_OBIEKTU { get; set; }
    
        public virtual ADRES_OBIEKTU ADRES_OBIEKTU { get; set; }
        public virtual ICollection<PRACOWNIK_OBIEKT> PRACOWNIK_OBIEKT { get; set; }
    }
}
