//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZYCJA
    {
        public POZYCJA()
        {
            this.ZAWODNIK = new HashSet<ZAWODNIK>();
        }
    
        public decimal ID_POZYCJI { get; set; }
        public string NAZWA_POZYCJI { get; set; }
    
        public virtual ICollection<ZAWODNIK> ZAWODNIK { get; set; }
    }
}
