//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacperTylutkiProjekt.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class STANOWISKO
    {
        public STANOWISKO()
        {
            this.PRACOWNIK = new HashSet<PRACOWNIK>();
        }
    
        public decimal ID_STANOWISKA { get; set; }
        public string NAZWA_STANOWISKA { get; set; }
    
        public virtual ICollection<PRACOWNIK> PRACOWNIK { get; set; }
    }
}
